apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-fusion-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pizza-fusion-frontend
  template:
    metadata:
      labels:
        app: pizza-fusion-frontend
    spec:
      containers:
      - name: pizza-fusion-frontend
        image: docker.io/docker380431/pizza-fusion-frontend:latest
        ports:
        - containerPort: 3000