apiVersion: v1
kind: Service
metadata:
  name: pizza-fusion-frontend-service
spec:
  selector:
    app: pizza-fusion-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP